### ISSUE TITLE
Song Postings

### ISSUE THREAD

**Issue by ryannguyen6392** [jakobreinwald/cs-130-project#6]
## Epic
Users should be able to share songs with their friends by posting it to their profile. The features include posting songs to profiles, engaging through friend feedback, and exploring a diverse range of music via the song-posting page. This will benefit users by allowing them to share music, engage in conversations, explore new music via their friends, and continue their personalized musical journey. 

## User Stories
- [ ] As a user, I want to select a song from my library to post
- [ ] As a user, I want to access my posts and others' posts on a song posting page
- [ ] As a user, I want to receive real-time notifications when my friends provide feedback on my post
